const ingredientsToBeSeeded = [
  { name: "Olive Oil", category: "OIL", tags: ["oil", "olive", "cooking"] },
  { name: "Butter", category: "DAIRY", tags: ["butter", "dairy", "fat"] },
  { name: "Salt", category: "SPICE", tags: ["salt", "seasoning"] },
  {
    name: "Black Pepper",
    category: "SPICE",
    tags: ["pepper", "spice", "seasoning"],
  },
  {
    name: "Carrot",
    category: "VEGETABLE",
    tags: ["carrot", "vegetable", "root"],
  },
  { name: "Apple", category: "FRUIT", tags: ["apple", "fruit", "sweet"] },
  {
    name: "Chicken Breast",
    category: "MEAT",
    tags: ["chicken", "meat", "poultry"],
  },
  { name: "Rice", category: "GRAIN", tags: ["rice", "grain", "starch"] },
  { name: "Almond", category: "NUT", tags: ["almond", "nut", "snack"] },
  { name: "Chia Seeds", category: "SEED", tags: ["chia", "seeds", "fiber"] },
  {
    name: "Lentils",
    category: "LEGUME",
    tags: ["lentils", "legume", "protein"],
  },
  { name: "Basil", category: "HERB", tags: ["basil", "herb", "aromatic"] },
  {
    name: "Ketchup",
    category: "CONDIMENT",
    tags: ["ketchup", "condiment", "sauce"],
  },
  { name: "Soy Sauce", category: "SAUCE", tags: ["soy", "sauce", "umami"] },
  { name: "Yogurt", category: "DAIRY", tags: ["yogurt", "dairy", "fermented"] },
  { name: "Cinnamon", category: "SPICE", tags: ["cinnamon", "spice", "sweet"] },
  { name: "Tomato", category: "FRUIT", tags: ["tomato", "fruit", "vegetable"] },
  {
    name: "Garlic",
    category: "VEGETABLE",
    tags: ["garlic", "aromatic", "vegetable"],
  },
  { name: "Beef", category: "MEAT", tags: ["beef", "meat", "protein"] },
  { name: "Oats", category: "GRAIN", tags: ["oats", "grain", "breakfast"] },
  { name: "Cashew", category: "NUT", tags: ["cashew", "nut", "snack"] },
  {
    name: "Sunflower Seeds",
    category: "SEED",
    tags: ["sunflower", "seeds", "snack"],
  },
  {
    name: "Chickpeas",
    category: "LEGUME",
    tags: ["chickpeas", "legume", "protein"],
  },
  { name: "Parsley", category: "HERB", tags: ["parsley", "herb", "garnish"] },
  {
    name: "Mayonnaise",
    category: "CONDIMENT",
    tags: ["mayonnaise", "condiment", "spread"],
  },
  { name: "Hot Sauce", category: "SAUCE", tags: ["hot", "sauce", "spicy"] },
  { name: "Cream", category: "DAIRY", tags: ["cream", "dairy", "rich"] },
  { name: "Nutmeg", category: "SPICE", tags: ["nutmeg", "spice", "baking"] },
  {
    name: "Onion",
    category: "VEGETABLE",
    tags: ["onion", "vegetable", "aromatic"],
  },
  { name: "Banana", category: "FRUIT", tags: ["banana", "fruit", "sweet"] },
  { name: "Pork", category: "MEAT", tags: ["pork", "meat", "protein"] },
  { name: "Quinoa", category: "GRAIN", tags: ["quinoa", "grain", "protein"] },
  { name: "Walnut", category: "NUT", tags: ["walnut", "nut", "omega-3"] },
  {
    name: "Pumpkin Seeds",
    category: "SEED",
    tags: ["pumpkin", "seeds", "snack"],
  },
  {
    name: "Black Beans",
    category: "LEGUME",
    tags: ["black beans", "legume", "fiber"],
  },
  { name: "Cilantro", category: "HERB", tags: ["cilantro", "herb", "fresh"] },
  {
    name: "Mustard",
    category: "CONDIMENT",
    tags: ["mustard", "condiment", "tangy"],
  },
  {
    name: "Barbecue Sauce",
    category: "SAUCE",
    tags: ["barbecue", "sauce", "bbq"],
  },
  { name: "Cheese", category: "DAIRY", tags: ["cheese", "dairy", "aged"] },
  {
    name: "Paprika",
    category: "SPICE",
    tags: ["paprika", "spice", "colorful"],
  },
  {
    name: "Spinach",
    category: "VEGETABLE",
    tags: ["spinach", "leafy", "green"],
  },
  { name: "Lemon", category: "FRUIT", tags: ["lemon", "citrus", "fruit"] },
  { name: "Turkey", category: "MEAT", tags: ["turkey", "meat", "poultry"] },
  { name: "Barley", category: "GRAIN", tags: ["barley", "grain", "fiber"] },
  { name: "Pecan", category: "NUT", tags: ["pecan", "nut", "dessert"] },
  { name: "Flax Seeds", category: "SEED", tags: ["flax", "seeds", "omega-3"] },
  {
    name: "Kidney Beans",
    category: "LEGUME",
    tags: ["kidney beans", "legume", "fiber"],
  },
  { name: "Thyme", category: "HERB", tags: ["thyme", "herb", "aromatic"] },
  {
    name: "Relish",
    category: "CONDIMENT",
    tags: ["relish", "condiment", "sweet"],
  },
  {
    name: "Tomato Sauce",
    category: "SAUCE",
    tags: ["tomato", "sauce", "pasta"],
  },
  {
    name: "Turmeric",
    category: "SPICE",
    tags: ["haldi", "turmeric", "spice", "yellow"],
  },
  {
    name: "Cumin Seeds",
    category: "SPICE",
    tags: ["jeera", "cumin", "spice", "seeds"],
  },
  {
    name: "Coriander Powder",
    category: "SPICE",
    tags: ["dhaniya", "coriander", "spice"],
  },
  {
    name: "Green Chili",
    category: "VEGETABLE",
    tags: ["green chili", "spicy", "vegetable"],
  },
  { name: "Mustard Oil", category: "OIL", tags: ["mustard", "oil", "cooking"] },
  {
    name: "Ginger",
    category: "VEGETABLE",
    tags: ["ginger", "adrak", "aromatic"],
  },
  {
    name: "Garlic Paste",
    category: "VEGETABLE",
    tags: ["garlic", "paste", "cooking"],
  },
  {
    name: "Red Chili Powder",
    category: "SPICE",
    tags: ["red chili", "spice", "powder", "hot"],
  },
  {
    name: "Asafoetida",
    category: "SPICE",
    tags: ["hing", "asafoetida", "spice"],
  },
  {
    name: "Fenugreek Seeds",
    category: "SEED",
    tags: ["methi", "fenugreek", "seeds"],
  },
  {
    name: "Curry Leaves",
    category: "HERB",
    tags: ["curry leaves", "kadi patta", "herb"],
  },
  {
    name: "Garam Masala",
    category: "SPICE",
    tags: ["garam masala", "blend", "spice"],
  },
  { name: "Tamarind", category: "FRUIT", tags: ["imli", "tamarind", "sour"] },
  {
    name: "Jaggery",
    category: "UNKNOWN",
    tags: ["jaggery", "gud", "sweetener"],
  },
  {
    name: "Basmati Rice",
    category: "GRAIN",
    tags: ["rice", "basmati", "grain"],
  },
  {
    name: "Urad Dal",
    category: "LEGUME",
    tags: ["urad dal", "legume", "black gram"],
  },
  {
    name: "Toor Dal",
    category: "LEGUME",
    tags: ["toor dal", "pigeon peas", "legume"],
  },
  {
    name: "Moong Dal",
    category: "LEGUME",
    tags: ["moong dal", "mung beans", "legume"],
  },
  {
    name: "Masoor Dal",
    category: "LEGUME",
    tags: ["masoor dal", "red lentils", "legume"],
  },
  { name: "Coconut Oil", category: "OIL", tags: ["coconut", "oil", "cooking"] },
  { name: "Paneer", category: "DAIRY", tags: ["paneer", "cheese", "dairy"] },
  { name: "Curd", category: "DAIRY", tags: ["curd", "dahi", "yogurt"] },
  {
    name: "Cardamom",
    category: "SPICE",
    tags: ["elaichi", "cardamom", "spice"],
  },
  { name: "Cloves", category: "SPICE", tags: ["cloves", "laung", "spice"] },
  {
    name: "Cinnamon Stick",
    category: "SPICE",
    tags: ["cinnamon", "dalchini", "stick"],
  },
  {
    name: "Bay Leaf",
    category: "HERB",
    tags: ["bay leaf", "tej patta", "herb"],
  },
  {
    name: "Black Cardamom",
    category: "SPICE",
    tags: ["black cardamom", "badi elaichi", "spice"],
  },
  {
    name: "Mustard Seeds",
    category: "SEED",
    tags: ["mustard", "rai", "seeds"],
  },
  {
    name: "Peanuts",
    category: "LEGUME",
    tags: ["peanuts", "groundnut", "snack"],
  },
  {
    name: "Poha",
    category: "GRAIN",
    tags: ["poha", "flattened rice", "grain"],
  },
  {
    name: "Sabudana",
    category: "GRAIN",
    tags: ["sabudana", "tapioca", "fasting food"],
  },
  {
    name: "Besan",
    category: "LEGUME",
    tags: ["besan", "gram flour", "chickpea"],
  },
  { name: "Wheat Flour", category: "GRAIN", tags: ["atta", "wheat", "flour"] },
  {
    name: "Maida",
    category: "GRAIN",
    tags: ["maida", "white flour", "refined"],
  },
  { name: "Rava", category: "GRAIN", tags: ["rava", "semolina", "grain"] },
  {
    name: "Amchur Powder",
    category: "SPICE",
    tags: ["amchur", "dry mango", "spice"],
  },
  {
    name: "Pomegranate Seeds",
    category: "FRUIT",
    tags: ["anardana", "pomegranate", "seeds"],
  },
  {
    name: "Dry Ginger Powder",
    category: "SPICE",
    tags: ["saunth", "dry ginger", "spice"],
  },
  { name: "Mint Leaves", category: "HERB", tags: ["mint", "pudina", "herb"] },
  {
    name: "Green Peas",
    category: "VEGETABLE",
    tags: ["green peas", "matar", "vegetable"],
  },
  {
    name: "Cauliflower",
    category: "VEGETABLE",
    tags: ["cauliflower", "gobi", "vegetable"],
  },
  {
    name: "Potato",
    category: "VEGETABLE",
    tags: ["potato", "aloo", "vegetable"],
  },
  {
    name: "Brinjal",
    category: "VEGETABLE",
    tags: ["brinjal", "baingan", "eggplant"],
  },
  {
    name: "Okra",
    category: "VEGETABLE",
    tags: ["okra", "bhindi", "vegetable"],
  },
  {
    name: "Bottle Gourd",
    category: "VEGETABLE",
    tags: ["lauki", "bottle gourd", "vegetable"],
  },
  {
    name: "Bitter Gourd",
    category: "VEGETABLE",
    tags: ["karela", "bitter gourd", "vegetable"],
  },
  {
    name: "Mango Pickle",
    category: "CONDIMENT",
    tags: ["mango pickle", "achar", "spicy"],
  },
  {
    name: "Ghee",
    category: "DAIRY",
    tags: ["ghee", "clarified butter", "dairy"],
  },
];

export { ingredientsToBeSeeded };
