const ingredientsToBeSeeded = [
  {
    name: "Olive Oil",
    category: "OIL",
    countOfRecipesUsedIn: 0,
    tags: ["oil", "olive", "cooking"],
  },
  {
    name: "Butter",
    category: "DAIRY",
    countOfRecipesUsedIn: 0,
    tags: ["butter", "dairy", "fat"],
  },
  {
    name: "Salt",
    category: "SPICE",
    countOfRecipesUsedIn: 0,
    tags: ["salt", "seasoning"],
  },
  {
    name: "Black Pepper",
    category: "SPICE",
    countOfRecipesUsedIn: 0,
    tags: ["pepper", "spice", "seasoning"],
  },
  {
    name: "Carrot",
    category: "VEGETABLE",
    countOfRecipesUsedIn: 0,
    tags: ["carrot", "vegetable", "root"],
  },
  {
    name: "Apple",
    category: "FRUIT",
    countOfRecipesUsedIn: 0,
    tags: ["apple", "fruit", "sweet"],
  },
  {
    name: "Chicken Breast",
    category: "MEAT",
    countOfRecipesUsedIn: 0,
    tags: ["chicken", "meat", "poultry"],
  },
  {
    name: "Rice",
    category: "GRAIN",
    countOfRecipesUsedIn: 0,
    tags: ["rice", "grain", "starch"],
  },
  {
    name: "Almond",
    category: "NUT",
    countOfRecipesUsedIn: 0,
    tags: ["almond", "nut", "snack"],
  },
  {
    name: "Chia Seeds",
    category: "SEED",
    countOfRecipesUsedIn: 0,
    tags: ["chia", "seeds", "fiber"],
  },
  {
    name: "Lentils",
    category: "LEGUME",
    countOfRecipesUsedIn: 0,
    tags: ["lentils", "legume", "protein"],
  },
  {
    name: "Basil",
    category: "HERB",
    countOfRecipesUsedIn: 0,
    tags: ["basil", "herb", "aromatic"],
  },
  {
    name: "Ketchup",
    category: "CONDIMENT",
    countOfRecipesUsedIn: 0,
    tags: ["ketchup", "condiment", "sauce"],
  },
  {
    name: "Soy Sauce",
    category: "SAUCE",
    countOfRecipesUsedIn: 0,
    tags: ["soy", "sauce", "umami"],
  },
  {
    name: "Yogurt",
    category: "DAIRY",
    countOfRecipesUsedIn: 0,
    tags: ["yogurt", "dairy", "fermented"],
  },
  {
    name: "Cinnamon",
    category: "SPICE",
    countOfRecipesUsedIn: 0,
    tags: ["cinnamon", "spice", "sweet"],
  },
  {
    name: "Tomato",
    category: "FRUIT",
    countOfRecipesUsedIn: 0,
    tags: ["tomato", "fruit", "vegetable"],
  },
  {
    name: "Garlic",
    category: "VEGETABLE",
    countOfRecipesUsedIn: 0,
    tags: ["garlic", "aromatic", "vegetable"],
  },
  {
    name: "Beef",
    category: "MEAT",
    countOfRecipesUsedIn: 0,
    tags: ["beef", "meat", "protein"],
  },
  {
    name: "Oats",
    category: "GRAIN",
    countOfRecipesUsedIn: 0,
    tags: ["oats", "grain", "breakfast"],
  },
  {
    name: "Cashew",
    category: "NUT",
    countOfRecipesUsedIn: 0,
    tags: ["cashew", "nut", "snack"],
  },
  {
    name: "Sunflower Seeds",
    category: "SEED",
    countOfRecipesUsedIn: 0,
    tags: ["sunflower", "seeds", "snack"],
  },
  {
    name: "Chickpeas",
    category: "LEGUME",
    countOfRecipesUsedIn: 0,
    tags: ["chickpeas", "legume", "protein"],
  },
  {
    name: "Parsley",
    category: "HERB",
    countOfRecipesUsedIn: 0,
    tags: ["parsley", "herb", "garnish"],
  },
  {
    name: "Mayonnaise",
    category: "CONDIMENT",
    countOfRecipesUsedIn: 0,
    tags: ["mayonnaise", "condiment", "spread"],
  },
  {
    name: "Hot Sauce",
    category: "SAUCE",
    countOfRecipesUsedIn: 0,
    tags: ["hot", "sauce", "spicy"],
  },
  {
    name: "Cream",
    category: "DAIRY",
    countOfRecipesUsedIn: 0,
    tags: ["cream", "dairy", "rich"],
  },
  {
    name: "Nutmeg",
    category: "SPICE",
    countOfRecipesUsedIn: 0,
    tags: ["nutmeg", "spice", "baking"],
  },
  {
    name: "Onion",
    category: "VEGETABLE",
    countOfRecipesUsedIn: 0,
    tags: ["onion", "vegetable", "aromatic"],
  },
  {
    name: "Banana",
    category: "FRUIT",
    countOfRecipesUsedIn: 0,
    tags: ["banana", "fruit", "sweet"],
  },
  {
    name: "Pork",
    category: "MEAT",
    countOfRecipesUsedIn: 0,
    tags: ["pork", "meat", "protein"],
  },
  {
    name: "Quinoa",
    category: "GRAIN",
    countOfRecipesUsedIn: 0,
    tags: ["quinoa", "grain", "protein"],
  },
  {
    name: "Walnut",
    category: "NUT",
    countOfRecipesUsedIn: 0,
    tags: ["walnut", "nut", "omega-3"],
  },
  {
    name: "Pumpkin Seeds",
    category: "SEED",
    countOfRecipesUsedIn: 0,
    tags: ["pumpkin", "seeds", "snack"],
  },
  {
    name: "Black Beans",
    category: "LEGUME",
    countOfRecipesUsedIn: 0,
    tags: ["black beans", "legume", "fiber"],
  },
  {
    name: "Cilantro",
    category: "HERB",
    countOfRecipesUsedIn: 0,
    tags: ["cilantro", "herb", "fresh"],
  },
  {
    name: "Mustard",
    category: "CONDIMENT",
    countOfRecipesUsedIn: 0,
    tags: ["mustard", "condiment", "tangy"],
  },
  {
    name: "Barbecue Sauce",
    category: "SAUCE",
    countOfRecipesUsedIn: 0,
    tags: ["barbecue", "sauce", "bbq"],
  },
  {
    name: "Cheese",
    category: "DAIRY",
    countOfRecipesUsedIn: 0,
    tags: ["cheese", "dairy", "aged"],
  },
  {
    name: "Paprika",
    category: "SPICE",
    countOfRecipesUsedIn: 0,
    tags: ["paprika", "spice", "colorful"],
  },
  {
    name: "Spinach",
    category: "VEGETABLE",
    countOfRecipesUsedIn: 0,
    tags: ["spinach", "leafy", "green"],
  },
  {
    name: "Lemon",
    category: "FRUIT",
    countOfRecipesUsedIn: 0,
    tags: ["lemon", "citrus", "fruit"],
  },
  {
    name: "Turkey",
    category: "MEAT",
    countOfRecipesUsedIn: 0,
    tags: ["turkey", "meat", "poultry"],
  },
  {
    name: "Barley",
    category: "GRAIN",
    countOfRecipesUsedIn: 0,
    tags: ["barley", "grain", "fiber"],
  },
  {
    name: "Pecan",
    category: "NUT",
    countOfRecipesUsedIn: 0,
    tags: ["pecan", "nut", "dessert"],
  },
  {
    name: "Flax Seeds",
    category: "SEED",
    countOfRecipesUsedIn: 0,
    tags: ["flax", "seeds", "omega-3"],
  },
  {
    name: "Kidney Beans",
    category: "LEGUME",
    countOfRecipesUsedIn: 0,
    tags: ["kidney beans", "legume", "fiber"],
  },
  {
    name: "Thyme",
    category: "HERB",
    countOfRecipesUsedIn: 0,
    tags: ["thyme", "herb", "aromatic"],
  },
  {
    name: "Relish",
    category: "CONDIMENT",
    countOfRecipesUsedIn: 0,
    tags: ["relish", "condiment", "sweet"],
  },
  {
    name: "Tomato Sauce",
    category: "SAUCE",
    countOfRecipesUsedIn: 0,
    tags: ["tomato", "sauce", "pasta"],
  },
  {
    name: "Turmeric",
    category: "SPICE",
    countOfRecipesUsedIn: 0,
    tags: ["haldi", "turmeric", "spice", "yellow"],
  },
  {
    name: "Cumin Seeds",
    category: "SPICE",
    countOfRecipesUsedIn: 0,
    tags: ["jeera", "cumin", "spice", "seeds"],
  },
  {
    name: "Coriander Powder",
    category: "SPICE",
    countOfRecipesUsedIn: 0,
    tags: ["dhaniya", "coriander", "spice"],
  },
  {
    name: "Green Chili",
    category: "VEGETABLE",
    countOfRecipesUsedIn: 0,
    tags: ["green chili", "spicy", "vegetable"],
  },
  {
    name: "Mustard Oil",
    category: "OIL",
    countOfRecipesUsedIn: 0,
    tags: ["mustard", "oil", "cooking"],
  },
  {
    name: "Ginger",
    category: "VEGETABLE",
    countOfRecipesUsedIn: 0,
    tags: ["ginger", "adrak", "aromatic"],
  },
  {
    name: "Garlic Paste",
    category: "VEGETABLE",
    countOfRecipesUsedIn: 0,
    tags: ["garlic", "paste", "cooking"],
  },
  {
    name: "Red Chili Powder",
    category: "SPICE",
    countOfRecipesUsedIn: 0,
    tags: ["red chili", "spice", "powder", "hot"],
  },
  {
    name: "Asafoetida",
    category: "SPICE",
    countOfRecipesUsedIn: 0,
    tags: ["hing", "asafoetida", "spice"],
  },
  {
    name: "Fenugreek Seeds",
    category: "SEED",
    countOfRecipesUsedIn: 0,
    tags: ["methi", "fenugreek", "seeds"],
  },
  {
    name: "Curry Leaves",
    category: "HERB",
    countOfRecipesUsedIn: 0,
    tags: ["curry leaves", "kadi patta", "herb"],
  },
  {
    name: "Garam Masala",
    category: "SPICE",
    countOfRecipesUsedIn: 0,
    tags: ["garam masala", "blend", "spice"],
  },
  {
    name: "Tamarind",
    category: "FRUIT",
    countOfRecipesUsedIn: 0,
    tags: ["imli", "tamarind", "sour"],
  },
  {
    name: "Jaggery",
    category: "UNKNOWN",
    countOfRecipesUsedIn: 0,
    tags: ["jaggery", "gud", "sweetener"],
  },
  {
    name: "Basmati Rice",
    category: "GRAIN",
    countOfRecipesUsedIn: 0,
    tags: ["rice", "basmati", "grain"],
  },
  {
    name: "Urad Dal",
    category: "LEGUME",
    countOfRecipesUsedIn: 0,
    tags: ["urad dal", "legume", "black gram"],
  },
  {
    name: "Toor Dal",
    category: "LEGUME",
    countOfRecipesUsedIn: 0,
    tags: ["toor dal", "pigeon peas", "legume"],
  },
  {
    name: "Moong Dal",
    category: "LEGUME",
    countOfRecipesUsedIn: 0,
    tags: ["moong dal", "mung beans", "legume"],
  },
  {
    name: "Masoor Dal",
    category: "LEGUME",
    countOfRecipesUsedIn: 0,
    tags: ["masoor dal", "red lentils", "legume"],
  },
  {
    name: "Coconut Oil",
    category: "OIL",
    countOfRecipesUsedIn: 0,
    tags: ["coconut", "oil", "cooking"],
  },
  {
    name: "Paneer",
    category: "DAIRY",
    countOfRecipesUsedIn: 0,
    tags: ["paneer", "cheese", "dairy"],
  },
  {
    name: "Curd",
    category: "DAIRY",
    countOfRecipesUsedIn: 0,
    tags: ["curd", "dahi", "yogurt"],
  },
  {
    name: "Cardamom",
    category: "SPICE",
    countOfRecipesUsedIn: 0,
    tags: ["elaichi", "cardamom", "spice"],
  },
  {
    name: "Cloves",
    category: "SPICE",
    countOfRecipesUsedIn: 0,
    tags: ["cloves", "laung", "spice"],
  },
  {
    name: "Cinnamon Stick",
    category: "SPICE",
    countOfRecipesUsedIn: 0,
    tags: ["cinnamon", "dalchini", "stick"],
  },
  {
    name: "Bay Leaf",
    category: "HERB",
    countOfRecipesUsedIn: 0,
    tags: ["bay leaf", "tej patta", "herb"],
  },
  {
    name: "Black Cardamom",
    category: "SPICE",
    countOfRecipesUsedIn: 0,
    tags: ["black cardamom", "badi elaichi", "spice"],
  },
  {
    name: "Mustard Seeds",
    category: "SEED",
    countOfRecipesUsedIn: 0,
    tags: ["mustard", "rai", "seeds"],
  },
  {
    name: "Peanuts",
    category: "LEGUME",
    countOfRecipesUsedIn: 0,
    tags: ["peanuts", "groundnut", "snack"],
  },
  {
    name: "Poha",
    category: "GRAIN",
    countOfRecipesUsedIn: 0,
    tags: ["poha", "flattened rice", "grain"],
  },
  {
    name: "Sabudana",
    category: "GRAIN",
    countOfRecipesUsedIn: 0,
    tags: ["sabudana", "tapioca", "fasting food"],
  },
  {
    name: "Besan",
    category: "LEGUME",
    countOfRecipesUsedIn: 0,
    tags: ["besan", "gram flour", "chickpea"],
  },
  {
    name: "Wheat Flour",
    category: "GRAIN",
    countOfRecipesUsedIn: 0,
    tags: ["atta", "wheat", "flour"],
  },
  {
    name: "Maida",
    category: "GRAIN",
    countOfRecipesUsedIn: 0,
    tags: ["maida", "white flour", "refined"],
  },
  {
    name: "Rava",
    category: "GRAIN",
    countOfRecipesUsedIn: 0,
    tags: ["rava", "semolina", "grain"],
  },
  {
    name: "Amchur Powder",
    category: "SPICE",
    countOfRecipesUsedIn: 0,
    tags: ["amchur", "dry mango", "spice"],
  },
  {
    name: "Pomegranate Seeds",
    category: "FRUIT",
    countOfRecipesUsedIn: 0,
    tags: ["anardana", "pomegranate", "seeds"],
  },
  {
    name: "Dry Ginger Powder",
    category: "SPICE",
    countOfRecipesUsedIn: 0,
    tags: ["saunth", "dry ginger", "spice"],
  },
  {
    name: "Mint Leaves",
    category: "HERB",
    countOfRecipesUsedIn: 0,
    tags: ["mint", "pudina", "herb"],
  },
  {
    name: "Green Peas",
    category: "VEGETABLE",
    countOfRecipesUsedIn: 0,
    tags: ["green peas", "matar", "vegetable"],
  },
  {
    name: "Cauliflower",
    category: "VEGETABLE",
    countOfRecipesUsedIn: 0,
    tags: ["cauliflower", "gobi", "vegetable"],
  },
  {
    name: "Potato",
    category: "VEGETABLE",
    countOfRecipesUsedIn: 0,
    tags: ["potato", "aloo", "vegetable"],
  },
  {
    name: "Brinjal",
    category: "VEGETABLE",
    countOfRecipesUsedIn: 0,
    tags: ["brinjal", "baingan", "eggplant"],
  },
  {
    name: "Okra",
    category: "VEGETABLE",
    countOfRecipesUsedIn: 0,
    tags: ["okra", "bhindi", "vegetable"],
  },
  {
    name: "Bottle Gourd",
    category: "VEGETABLE",
    countOfRecipesUsedIn: 0,
    tags: ["lauki", "bottle gourd", "vegetable"],
  },
  {
    name: "Bitter Gourd",
    category: "VEGETABLE",
    countOfRecipesUsedIn: 0,
    tags: ["karela", "bitter gourd", "vegetable"],
  },
  {
    name: "Mango Pickle",
    category: "CONDIMENT",
    countOfRecipesUsedIn: 0,
    tags: ["mango pickle", "achar", "spicy"],
  },
  {
    name: "Ghee",
    category: "DAIRY",
    countOfRecipesUsedIn: 0,
    tags: ["ghee", "clarified butter", "dairy"],
  },
];

export { ingredientsToBeSeeded };
